// Generated by Claude (Anthropic, Claude Opus 5.5) for the Metal GEMM worklog.
// Not written by the repository author. Last run on an Apple M5 on 2026-09-25.
// See probes/README.md for commands and recorded results.

import Foundation
import Metal
let dev = MTLCreateSystemDefaultDevice()!
let src = """
#include <metal_stdlib>
using namespace metal;
template <int CHAINS, int UNROLL>
kernel void fma_peak(device float* out [[buffer(0)]], constant uint& iters [[buffer(1)]], uint gid [[thread_position_in_grid]]) {
  float a[CHAINS];
  for (int c = 0; c < CHAINS; ++c) a[c] = float(gid + c) * 1e-7f;
  const float m = 0.9999f, b = 0.0001f;
  for (uint it = 0; it < iters; ++it) {
    #pragma unroll
    for (int u = 0; u < UNROLL; ++u) {
      #pragma unroll
      for (int c = 0; c < CHAINS; ++c) a[c] = fma(a[c], m, b);
    }
  }
  float s = 0.f;
  for (int c = 0; c < CHAINS; ++c) s += a[c];
  out[gid] = s;
}
template [[host_name("c4u16")]]  kernel void fma_peak<4,16>(device float*, constant uint&, uint);
template [[host_name("c8u8")]]   kernel void fma_peak<8,8>(device float*, constant uint&, uint);
template [[host_name("c12u8")]]  kernel void fma_peak<12,8>(device float*, constant uint&, uint);
template [[host_name("c16u4")]]  kernel void fma_peak<16,4>(device float*, constant uint&, uint);
template [[host_name("c32u2")]]  kernel void fma_peak<32,2>(device float*, constant uint&, uint);
"""
let lib = try! dev.makeLibrary(source: src, options: nil)
let q = dev.makeCommandQueue()!
let out = dev.makeBuffer(length: (1 << 22) * 4, options: .storageModePrivate)!
for (name, perIt) in [("c4u16", 64), ("c8u8", 64), ("c12u8", 96), ("c16u4", 64), ("c32u2", 64)] {
  let p = try! dev.makeComputePipelineState(function: lib.makeFunction(name: name)!)
  for threads in [1 << 18, 1 << 20] { for tg in [128, 256, 512] {
    var iters: UInt32 = threads == 1 << 18 ? 2048 : 512
    var ts: [Double] = []
    for r in 0..<9 {
      let cb = q.makeCommandBuffer()!; let e = cb.makeComputeCommandEncoder()!
      e.setComputePipelineState(p); e.setBuffer(out, offset: 0, index: 0); e.setBytes(&iters, length: 4, index: 1)
      e.dispatchThreads(MTLSize(width: threads, height: 1, depth: 1), threadsPerThreadgroup: MTLSize(width: tg, height: 1, depth: 1))
      e.endEncoding(); cb.commit(); cb.waitUntilCompleted()
      if r >= 2 { ts.append(cb.gpuEndTime - cb.gpuStartTime) }
    }
    ts.sort()
    let fl = Double(threads) * Double(iters) * Double(perIt) * 2
    print(String(format: "%@ thr=%7d tg=%3d regs? maxT=%4d  %.2f ms  median %.3f  best %.3f TFLOP/s", name, threads, tg, p.maxTotalThreadsPerThreadgroup, ts[ts.count/2]*1e3, fl/ts[ts.count/2]/1e12, fl/ts[0]/1e12))
  } }
}
