// Generated by Claude (Anthropic, Claude Opus 5.5) for the Metal GEMM worklog.
// Not written by the repository author. Last run on an Apple M5 on 2026-09-25.
// See probes/README.md for commands and recorded results.

import Foundation
import Metal
import MetalPerformanceShaders

// Probes for the Metal GEMM post. All times are GPU timestamps
// (MTLCommandBuffer.gpuStartTime/gpuEndTime), median of N reps after warmup.

let dev = MTLCreateSystemDefaultDevice()!
print("device:", dev.name, "arch:", dev.architecture.name)
print("maxThreadgroupMemoryLength:", dev.maxThreadgroupMemoryLength)
print("recommendedMaxWorkingSetSize GB:", Double(dev.recommendedMaxWorkingSetSize) / 1e9)

let src = """
#include <metal_stdlib>
using namespace metal;
struct GemmShape { uint M; uint N; uint K; };

kernel void simd_layout(device uint4* out [[buffer(0)]],
                        uint2 tp [[thread_position_in_threadgroup]],
                        uint tidx [[thread_index_in_threadgroup]],
                        uint sg [[simdgroup_index_in_threadgroup]],
                        uint lane [[thread_index_in_simdgroup]],
                        uint w [[threads_per_simdgroup]]) {
  out[tp.y * 32 + tp.x] = uint4(tidx, sg, lane, w);
}

template <int CHAINS>
kernel void fma_peak(device float* out [[buffer(0)]],
                     constant uint& iters [[buffer(1)]],
                     uint gid [[thread_position_in_grid]]) {
  float a[CHAINS];
  for (int c = 0; c < CHAINS; ++c) a[c] = float(gid + c) * 1e-7f;
  const float m = 0.9999f, b = 0.0001f;
  for (uint it = 0; it < iters; ++it) {
    #pragma unroll
    for (int c = 0; c < CHAINS; ++c) a[c] = fma(a[c], m, b);
  }
  float s = 0.f;
  for (int c = 0; c < CHAINS; ++c) s += a[c];
  out[gid] = s;
}
template [[host_name("fma4")]]  kernel void fma_peak<4>(device float*, constant uint&, uint);
template [[host_name("fma8")]]  kernel void fma_peak<8>(device float*, constant uint&, uint);
template [[host_name("fma16")]] kernel void fma_peak<16>(device float*, constant uint&, uint);

kernel void read_bw(device const float4* in [[buffer(0)]],
                    device float* out [[buffer(1)]],
                    constant uint& n4 [[buffer(2)]],
                    uint gid [[thread_position_in_grid]],
                    uint gsz [[threads_per_grid]]) {
  float4 s = 0;
  for (uint i = gid; i < n4; i += gsz) s += in[i];
  float t = s.x + s.y + s.z + s.w;
  if (t == 1234.5f) out[gid] = t;
}

kernel void copy_bw(device const float4* in [[buffer(0)]],
                    device float4* out [[buffer(1)]],
                    uint gid [[thread_position_in_grid]]) {
  out[gid] = in[gid];
}

// Exactly the post's naive kernel: x -> column j, y -> row i.
kernel void naive_xcol(device const float* A [[buffer(0)]], device const float* B [[buffer(1)]],
                       device float* C [[buffer(2)]], device const GemmShape& p [[buffer(3)]],
                       uint2 bp [[threadgroup_position_in_grid]], uint2 tp [[thread_position_in_threadgroup]],
                       uint2 tpg [[threads_per_threadgroup]]) {
  const uint j = bp.x * tpg.x + tp.x;
  const uint i = bp.y * tpg.y + tp.y;
  if (i < p.M && j < p.N) {
    float sum = 0.f;
    for (uint k = 0; k < p.K; ++k) sum += A[i * p.K + k] * B[k * p.N + j];
    C[i * p.N + j] = sum;
  }
}

// Flipped: x -> row i, y -> column j (Simon's kernel 1 mapping).
kernel void naive_xrow(device const float* A [[buffer(0)]], device const float* B [[buffer(1)]],
                       device float* C [[buffer(2)]], device const GemmShape& p [[buffer(3)]],
                       uint2 bp [[threadgroup_position_in_grid]], uint2 tp [[thread_position_in_threadgroup]],
                       uint2 tpg [[threads_per_threadgroup]]) {
  const uint i = bp.x * tpg.x + tp.x;
  const uint j = bp.y * tpg.y + tp.y;
  if (i < p.M && j < p.N) {
    float sum = 0.f;
    for (uint k = 0; k < p.K; ++k) sum += A[i * p.K + k] * B[k * p.N + j];
    C[i * p.N + j] = sum;
  }
}
"""

let lib = try! dev.makeLibrary(source: src, options: nil)
func pso(_ name: String) -> MTLComputePipelineState {
  try! dev.makeComputePipelineState(function: lib.makeFunction(name: name)!)
}
let queue = dev.makeCommandQueue()!

func gpuTime(reps: Int = 10, warmup: Int = 2, _ encode: (MTLComputeCommandEncoder) -> Void) -> [Double] {
  var ts: [Double] = []
  for r in 0..<(reps + warmup) {
    let cb = queue.makeCommandBuffer()!
    let enc = cb.makeComputeCommandEncoder()!
    encode(enc)
    enc.endEncoding()
    cb.commit()
    cb.waitUntilCompleted()
    if r >= warmup { ts.append(cb.gpuEndTime - cb.gpuStartTime) }
  }
  return ts.sorted()
}
func median(_ a: [Double]) -> Double { a[a.count / 2] }

let args = CommandLine.arguments
let which = args.count > 1 ? args[1] : "all"

// 1. SIMD-group layout of a 32x32 threadgroup.
if which == "all" || which == "layout" {
  let p = pso("simd_layout")
  print("simd_layout threadExecutionWidth:", p.threadExecutionWidth, "maxTotalThreadsPerThreadgroup:", p.maxTotalThreadsPerThreadgroup)
  let buf = dev.makeBuffer(length: 1024 * 16, options: .storageModeShared)!
  _ = gpuTime(reps: 1, warmup: 0) { e in
    e.setComputePipelineState(p); e.setBuffer(buf, offset: 0, index: 0)
    e.dispatchThreadgroups(MTLSize(width: 1, height: 1, depth: 1), threadsPerThreadgroup: MTLSize(width: 32, height: 32, depth: 1))
  }
  let v = buf.contents().bindMemory(to: SIMD4<UInt32>.self, capacity: 1024)
  var ok = true
  for y in 0..<32 { for x in 0..<32 {
    let r = v[y * 32 + x]
    if r.x != UInt32(y * 32 + x) || r.y != UInt32(y) || r.z != UInt32(x) || r.w != 32 { ok = false }
  } }
  print("32x32 group: simdgroup == row y, lane == x, linear == x + 32y :", ok)
  for (x, y) in [(0, 0), (31, 0), (0, 1), (5, 7)] {
    let r = v[y * 32 + x]; print("  (x=\(x), y=\(y)) -> linear \(r.x), simdgroup \(r.y), lane \(r.z), width \(r.w)")
  }
  // 16x16 group: a SIMD group of 32 must span two rows.
  let buf2 = dev.makeBuffer(length: 1024 * 16, options: .storageModeShared)!
  let p16 = p
  _ = gpuTime(reps: 1, warmup: 0) { e in
    e.setComputePipelineState(p16); e.setBuffer(buf2, offset: 0, index: 0)
    e.dispatchThreadgroups(MTLSize(width: 1, height: 1, depth: 1), threadsPerThreadgroup: MTLSize(width: 16, height: 16, depth: 1))
  }
  let v2 = buf2.contents().bindMemory(to: SIMD4<UInt32>.self, capacity: 1024)
  for (x, y) in [(0, 0), (15, 0), (0, 1), (15, 1), (0, 2)] {
    let r = v2[y * 32 + x]; print("  16x16 (x=\(x), y=\(y)) -> linear \(r.x), simdgroup \(r.y), lane \(r.z)")
  }
}

// 2. FP32 FMA peak.
if which == "all" || which == "fma" {
  let out = dev.makeBuffer(length: (1 << 22) * 4, options: .storageModePrivate)!
  var iters: UInt32 = 4096
  for name in ["fma4", "fma8", "fma16"] {
    let p = pso(name)
    let chains = Double(Int(name.dropFirst(3))!)
    for threads in [1 << 18, 1 << 20, 1 << 22] {
      for tg in [256, 1024] {
        let t = gpuTime(reps: 7) { e in
          e.setComputePipelineState(p); e.setBuffer(out, offset: 0, index: 0)
          e.setBytes(&iters, length: 4, index: 1)
          e.dispatchThreads(MTLSize(width: threads, height: 1, depth: 1), threadsPerThreadgroup: MTLSize(width: tg, height: 1, depth: 1))
        }
        let flops = Double(threads) * Double(iters) * chains * 2
        print(String(format: "%@ threads=%8d tg=%4d  %.3f ms  %.3f TFLOP/s (best %.3f)", name, threads, tg, median(t) * 1e3, flops / median(t) / 1e12, flops / t[0] / 1e12))
      }
    }
  }
}

// 3. DRAM bandwidth.
if which == "all" || which == "bw" {
  let bytes = 1 << 30
  let a = dev.makeBuffer(length: bytes, options: .storageModePrivate)!
  let b = dev.makeBuffer(length: bytes, options: .storageModePrivate)!
  let small = dev.makeBuffer(length: 1 << 26, options: .storageModePrivate)!
  // Fill a with something via blit.
  let cb = queue.makeCommandBuffer()!; let bl = cb.makeBlitCommandEncoder()!
  bl.fill(buffer: a, range: 0..<bytes, value: 1); bl.endEncoding(); cb.commit(); cb.waitUntilCompleted()
  let rp = pso("read_bw")
  var n4 = UInt32(bytes / 16)
  for threads in [1 << 16, 1 << 18, 1 << 20] {
    let t = gpuTime(reps: 10) { e in
      e.setComputePipelineState(rp); e.setBuffer(a, offset: 0, index: 0); e.setBuffer(small, offset: 0, index: 1)
      e.setBytes(&n4, length: 4, index: 2)
      e.dispatchThreads(MTLSize(width: threads, height: 1, depth: 1), threadsPerThreadgroup: MTLSize(width: 256, height: 1, depth: 1))
    }
    print(String(format: "read  1 GiB threads=%7d  %.3f ms  %.1f GB/s (best %.1f)", threads, median(t) * 1e3, Double(bytes) / median(t) / 1e9, Double(bytes) / t[0] / 1e9))
  }
  let cp = pso("copy_bw")
  let t = gpuTime(reps: 10) { e in
    e.setComputePipelineState(cp); e.setBuffer(a, offset: 0, index: 0); e.setBuffer(b, offset: 0, index: 1)
    e.dispatchThreads(MTLSize(width: bytes / 16, height: 1, depth: 1), threadsPerThreadgroup: MTLSize(width: 256, height: 1, depth: 1))
  }
  print(String(format: "copy  1 GiB (read+write 2 GiB)  %.3f ms  %.1f GB/s (best %.1f)", median(t) * 1e3, 2 * Double(bytes) / median(t) / 1e9, 2 * Double(bytes) / t[0] / 1e9))
}

// 4. Naive mapping comparison + MPS, 4096^3, GPU time.
if which == "all" || which == "naive" {
  let n = 4096
  let bytes = n * n * 4
  func randBuf() -> MTLBuffer {
    let buf = dev.makeBuffer(length: bytes, options: .storageModeShared)!
    let p = buf.contents().bindMemory(to: Float.self, capacity: n * n)
    for i in 0..<(n * n) { p[i] = Float((i * 2654435761) % 1000) / 1000 - 0.5 }
    return buf
  }
  let A = randBuf(), B = randBuf()
  let C1 = dev.makeBuffer(length: bytes, options: .storageModeShared)!
  let C2 = dev.makeBuffer(length: bytes, options: .storageModeShared)!
  var shape: (UInt32, UInt32, UInt32) = (UInt32(n), UInt32(n), UInt32(n))
  let flops = 2.0 * Double(n) * Double(n) * Double(n)
  var results: [String: [Double]] = [:]
  for (name, C) in [("naive_xcol", C1), ("naive_xrow", C2)] {
    let p = pso(name)
    for tgw in [32, 16, 8] {
      let groups = n / tgw
      let t = gpuTime(reps: 5, warmup: 1) { e in
        e.setComputePipelineState(p)
        e.setBuffer(A, offset: 0, index: 0); e.setBuffer(B, offset: 0, index: 1); e.setBuffer(C, offset: 0, index: 2)
        e.setBytes(&shape, length: 12, index: 3)
        e.dispatchThreadgroups(MTLSize(width: groups, height: groups, depth: 1), threadsPerThreadgroup: MTLSize(width: tgw, height: tgw, depth: 1))
      }
      results["\(name)_\(tgw)"] = t
      print(String(format: "%@ tg=%2dx%-2d  median %.2f ms  %.1f GFLOP/s  (min %.2f max %.2f)", name, tgw, tgw, median(t) * 1e3, flops / median(t) / 1e9, t.first! * 1e3, t.last! * 1e3))
    }
  }
  let c1 = C1.contents().bindMemory(to: Float.self, capacity: n * n)
  let c2 = C2.contents().bindMemory(to: Float.self, capacity: n * n)
  var maxd: Float = 0
  for i in stride(from: 0, to: n * n, by: 997) { maxd = max(maxd, abs(c1[i] - c2[i])) }
  print("xcol vs xrow max abs diff (sampled):", maxd)

  // MPS FP32 GPU time.
  let desc = MPSMatrixDescriptor(rows: n, columns: n, rowBytes: n * 4, dataType: .float32)
  let mA = MPSMatrix(buffer: A, descriptor: desc), mB = MPSMatrix(buffer: B, descriptor: desc)
  let mC = MPSMatrix(buffer: C1, descriptor: desc)
  let mm = MPSMatrixMultiplication(device: dev, transposeLeft: false, transposeRight: false, resultRows: n, resultColumns: n, interiorColumns: n, alpha: 1, beta: 0)
  var ts: [Double] = []
  for r in 0..<12 {
    let cb = queue.makeCommandBuffer()!
    mm.encode(commandBuffer: cb, leftMatrix: mA, rightMatrix: mB, resultMatrix: mC)
    cb.commit(); cb.waitUntilCompleted()
    if r >= 2 { ts.append(cb.gpuEndTime - cb.gpuStartTime) }
  }
  ts.sort()
  print(String(format: "MPS fp32 4096^3 GPU median %.2f ms  %.1f GFLOP/s (min %.2f max %.2f)", median(ts) * 1e3, flops / median(ts) / 1e9, ts.first! * 1e3, ts.last! * 1e3))
}
