// Generated by Claude (Anthropic, Claude Opus 5.5) for the Metal GEMM worklog.
// Not written by the repository author. Last run on an Apple M5 on 2026-09-25.
// See probes/README.md for commands and recorded results.

import Metal
import MetalPerformanceShaders
let dev = MTLCreateSystemDefaultDevice()!
let q = dev.makeCommandQueue()!
let n = 4096
for (dt, sz, name) in [(MPSDataType.float16, 2, "fp16"), (MPSDataType.float32, 4, "fp32")] {
  let bytes = n * n * sz
  let A = dev.makeBuffer(length: bytes, options: .storageModePrivate)!, B = dev.makeBuffer(length: bytes, options: .storageModePrivate)!, C = dev.makeBuffer(length: bytes, options: .storageModePrivate)!
  let d = MPSMatrixDescriptor(rows: n, columns: n, rowBytes: n * sz, dataType: dt)
  let mm = MPSMatrixMultiplication(device: dev, transposeLeft: false, transposeRight: false, resultRows: n, resultColumns: n, interiorColumns: n, alpha: 1, beta: 0)
  var ts: [Double] = []
  for r in 0..<12 {
    let cb = q.makeCommandBuffer()!
    mm.encode(commandBuffer: cb, leftMatrix: MPSMatrix(buffer: A, descriptor: d), rightMatrix: MPSMatrix(buffer: B, descriptor: d), resultMatrix: MPSMatrix(buffer: C, descriptor: d))
    cb.commit(); cb.waitUntilCompleted()
    if r >= 2 { ts.append(cb.gpuEndTime - cb.gpuStartTime) }
  }
  ts.sort()
  print(name, String(format: "median %.2f ms  %.2f TFLOP/s", ts[5]*1e3, 2*Double(n*n*n)/ts[5]/1e12))
}
